version: "3.8"
services:
  postgres-db:
    container_name: infinity-postgres-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - PGDATA=/pgdata
      - POSTGRES_DB=test_db
    restart:  unless-stopped
    networks:
      - infinity-network

networks:
  infinity-network:
    name: infinity-network