DROP DATABASE IF EXISTS Infinity;
CREATE DATABASE test_db;
DROP USER IF EXISTS infinity;
CREATE USER infinity WITH ENCRYPTED PASSWORD 'password';
GRANT ALL PRIVILEGES ON DATABASE test_db TO infinity;
GRANT ALL ON SCHEMA public TO infinity;